[package]
name = "nbody"
version = "1.0.0"
edition = "2021"

[dependencies]
wgpu = "0.14"
winit = "0.27"
encase = { version = "0.4", features = ["glam"] }
bytemuck = "1.12"
pollster = "0.2"
glam = "0.22"
futures-intrusive = "0.5"
rand = "0.8"
